version: '3.7'
services:
    api:
        shm_size: '1000000000'
        build:
            context: ./api
        tty: true
    nginx:
        build: ./nginx
        tty: true
        links:
            - api
        ports:
            - '5000:5000'
